### ISSUE TITLE
Most(If not all) items doesn't get dropped as an item when broken with valid methods.

### ISSUE THREAD

**Issue by oknacupZero** [ZLT9/create-vibrant-vaults#1]
Wrench also doesn't work.
I didn't test all of them but this should be enough.
![2024-07-21 16-26-13](https://github.com/user-attachments/assets/10592664-f8b2-4464-9800-5ebc76957f37)

**Comment by ZLT9** [comment]
Fixed in [version 0.1.1](https://modrinth.com/mod/create-vibrant-vaults/version/0.1.1+mc1.20.1). Thanks for reporting!
