### ISSUE TITLE
Port To Forge?

### ISSUE THREAD

**Issue by CodedtoonCactus** [ZLT9/create-vibrant-vaults#2]
I like the look of this mod, and want to add it to an instance on Modrinth as well as a potential Modpack I want to make, but this mod is for Fabric, and the instance and planned Modpack (which quite a few mods need to) rely on Forge.

**Comment by ZLT9** [comment]
Hi, thank you so much for your interest in Create: Vibrant Vaults! I appreciate your feedback and the suggestion to port it to Forge.

I'm happy to let you know that I've now released a Forge version of the mod on Modrinth. You can find it in the versions tab and use it for your instance or modpack. If you encounter any issues or have further suggestions, feel free to reach out.

Thank you again for your patience and support!
